import { Game } from './types';

export const initialGameData: Game = {
	id: 'GeopoliticalShock2025',
	key: 'DNB_2025_R1',
	name: 'Insurance Simulation',
	rounds: [
		{
			round_id: 'round_1',
			round_duration: 3600,
			round_started_at: null,
			round_finished_at: null,
			round_index: 0,
			round_name: 'Round 1: Initial Investments',
			choices: [
				{
					id: '1',
					description: 'Investeer in onderzoek',
					expected_profit_score: -10,
					liquidity_score: 5,
					solvency_score: 2,
					IT_score: -1,
					capacity_score: 4,
					duration: 1,
					reveals: [
						{
							text: 'Onderzoek toont aan dat er een nieuwe technologie op de markt komt die de productiekosten aanzienlijk verlaagt.',
							revealedInRounds: 1,
						},
						{
							text: 'De technologie heeft een onverwachte bijwerking, wat leidt tot vertragingen in de implementatie.',
							revealedInRounds: 2,
						},
					],
					interactionEffects: [
						{ targetChoiceId: '2', roundId: 'round_2', bonusScore: 25 },
					],
				},
				{
					id: '2',
					description: 'Update bedrijfsmodellen',
					expected_profit_score: 20,
					liquidity_score: -5,
					solvency_score: 1,
					IT_score: 3,
					capacity_score: 2,
					duration: 2,
					reveals: [
						{
							text: 'De geüpdate modellen zijn zeer efficiënt en verhogen de inkomsten.',
							revealedInRounds: 2,
						},
						{
							text: 'Concurrenten hebben uw nieuwe model snel gekopieerd, wat de winstmarges doet dalen.',
							revealedInRounds: 3,
						},
					],
					interactionEffects: [],
				},
				{
					id: '3',
					description: 'Onderzoek China',
					expected_profit_score: 30,
					liquidity_score: -2,
					solvency_score: 0,
					IT_score: 0,
					capacity_score: 2,
					duration: 1,
					reveals: [
						{
							text: 'Onderzoek toont een grote, onontdekte markt in China met hoge winstkansen.',
							revealedInRounds: 1,
						},
					],
					interactionEffects: [],
				},
			],
		},
		{
			round_id: 'round_2',
			round_duration: 3600,
			round_started_at: null,
			round_finished_at: null,
			round_index: 1,
			round_name: 'Round 2: Market Expansion',
			choices: [
				{
					id: '1',
					description: 'Breid uit naar Europa',
					expected_profit_score: 15,
					liquidity_score: 10,
					solvency_score: 3,
					IT_score: 2,
					capacity_score: 3,
					duration: 1,
					reveals: [],
					interactionEffects: [],
				},
				{
					id: '2',
					description: 'Focus op binnenlandse markt',
					expected_profit_score: 10,
					liquidity_score: 5,
					solvency_score: 1,
					IT_score: 1,
					capacity_score: 5,
					duration: 1,
					reveals: [],
					interactionEffects: [],
				},
				{
					id: '3',
					description: 'Verwerf een concurrent',
					expected_profit_score: 40,
					liquidity_score: -15,
					solvency_score: 5,
					IT_score: 4,
					capacity_score: 1,
					duration: 1,
					reveals: [],
					interactionEffects: [],
				},
			],
		},
		{
			round_id: 'round_3',
			round_duration: 3600,
			round_started_at: null,
			round_finished_at: null,
			round_index: 2,
			round_name: 'Round 3: Vervolg',
			choices: [
				{
					id: '1',
					description: 'Breid uit naar Europa',
					expected_profit_score: 15,
					liquidity_score: 10,
					solvency_score: 3,
					IT_score: 2,
					capacity_score: 3,
					duration: 1,
					reveals: [],
					interactionEffects: [],
				},
				{
					id: '2',
					description: 'Focus op binnenlandse markt',
					expected_profit_score: 10,
					liquidity_score: 5,
					solvency_score: 1,
					IT_score: 1,
					capacity_score: 5,
					duration: 1,
					reveals: [],
					interactionEffects: [],
				},
			],
		},
	],
	teams: [
		{
			id: 'team_1',
			teamName: 'Verzekerbaars',
			choices: [],
			expected_profit_score: 0,
			liquidity_score: 0,
			solvency_score: 0,
			IT_score: 0,
			capacity_score: 7,
		},
		{
			id: 'team_2',
			teamName: 'Financieel Fijntjes',
			choices: [],
			expected_profit_score: 0,
			liquidity_score: 0,
			solvency_score: 0,
			IT_score: 0,
			capacity_score: 7,
		},
	],
	currentRoundIndex: 0,
	currentRoundId: 'round_1',
	gameStartedAt: null,
	gameFinishedAt: null,
	createdAt: Date.now(),
};
